# Gunakan image Python dasar
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy semua file aplikasi
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port untuk app
EXPOSE 5000

# Gunakan gunicorn untuk production
CMD ["gunicorn", "-b", "0.0.0.0:5000", "run:app"]
